name: Rust

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check-no-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: cargo check --no-default-features 
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
        - slip10
        - slip10,curve-secp256k1
        - slip10,curve-secp256r1
        - edwards
        - stark
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: cargo check --features ${{ matrix.features }} 
  check-and-test-all-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: cargo check --all-features
    - name: Run tests
      run: cargo test --all-features --lib --tests
  doctest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Doctests
      run: cargo test --doc --all-features
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - name: Check formatting
      run: cargo fmt --all -- --check
  check-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Run clippy
      run: cargo clippy -- -D clippy::all
  check-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - name: Check changelogs
      run: ./.github/changelog.sh
    
